services:
  solr_setup:
    image: solr:9
    user: root
    command: bash -c "chown -R 8983:8983 /var/solr"
    volumes:
      - ${SOLR_INDEX_PATH}:/var/solr
      - ${SOLR_LOG_PATH}:/var/solr/logs
  solr:
    image: solr:9
    restart: unless-stopped
    container_name: ${CONTAINER_NAME}
    depends_on:
      - solr_setup
    ports:
      - "${CONTAINER_PORT}:8983"
    env_file:
      - .env
    environment:
      - SOLR_HOST=${SOLR_HOST}
      - SOLR_HEAP=${SOLR_MEMORY}
    volumes:
      - ${SOLR_INDEX_PATH}:/var/solr
      - ${SOLR_LOG_PATH}:/var/solr/logs
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
