version: '2.4'

services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy:latest
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    networks:
      - nginx-proxy
    container_name: nginx-proxy
    mem_limit: 128m

networks:
  nginx-proxy:
    external: true

