version: '3'

services:
  dremio:
    image: dremio/dremio-oss:24.3
    container_name: dremio
    volumes:
      - ./localFiles:/localFiles
      - ./conf:/opt/dremio/conf
      - data:/opt/dremio/data
    environment:
      - MASTER_CONTAINER_IP=${MASTER_CONTAINER_IP}

volumes:
   data:
