version: '2.4'

services:
  catalina1:
    container_name: catalina1
    restart: always
    mem_limit: 128m
    build: ./catalina/
    environment:
      - VIRTUAL_HOST=catalina1.teste.bireme.org
    networks:
      - nginx-proxy

  catalina2:
    container_name: catalina2
    restart: always
    mem_limit: 128m
    image: tomcat_catalina1
    environment:
      - VIRTUAL_HOST=catalina2.teste.bireme.org
    depends_on: 
      - catalina1
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
