services:
  srv-tomcat:
    build:
      context: .
    image: bireme/tomcat7:1.0
    container_name: srv-tomcat
    restart: unless-stopped
    environment:
      CATALINA_OPTS: ${CATALINA_OPTS}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
    volumes:
      - ${WEBAPPS_PATH}:/usr/local/tomcat/webapps
      - ${LOG_PATH}:/usr/local/tomcat/logs
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
