default: build

## prod shortcuts
build:
	@docker compose build

run:
	@docker compose up

start:
	@docker compose up -d

stop:
	@docker compose stop

logs:
	@docker compose logs -f

ps:
	@docker compose ps

shell:
	@docker compose exec srv-tomcat sh
