services:
  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=false

  loki:
    image: grafana/loki:latest
    container_name: grafana-loki
    ports:
      - ${LOKI_PORT}:3100
    volumes:
      - ./config/loki-local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

