run:
	@docker-compose up

run_grafana:
	@docker-compose up grafana

run_loki:
	@docker-compose up loki

start:
	@docker-compose up -d

start_grafana:
	@docker-compose up -d grafana

start_loki:
	@docker-compose up -d loki

stop:
	@docker-compose stop

stop_grafana:
	@docker-compose stop grafana

stop_loki:
	@docker-compose stop loki

logs:
	@docker-compose logs -f

ps:
	@docker-compose ps

sh_grafana:
	@docker-compose exec grafana sh

sh_loki:
	@docker-compose exec loki sh

