version: '3'
services:
  uptime:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    expose:
      - "3001"
    volumes:
      - ${APP_DATA_PATH}:/app/data
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true