services:
  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    container_name: "minio"
    restart: unless-stopped
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - ./s3_objects:/data
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
