FROM docker.io/bitnami/solr:9.9.0

# Copy decs lucene index
COPY ./resources/decs /opt/bitnami/solr/server/resources/decs

# Copy custom iahx analyzers to solr webapp lib folder
# COPY ./lib /opt/bitnami/solr/server/solr-webapp/webapp/WEB-INF/lib

