version: '2.4'

services:
  portainer:
    container_name: portainer
    restart: unless-stopped
    mem_limit: 32m
    image: portainer/portainer-ce:latest
    volumes:
      - 'data:/data:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    ports:
      - '8090:9000'

volumes:
  data:
