version: '3'

services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail-send-logs
    restart: always    
    volumes:
      - ./conf:/etc/promtail
      - ${PATH_LOGS}:/var/log
    command: -config.file=/etc/promtail/config.yml
